Module7 task3
htmlacademy-react/1608929-what-to-watch-8 pull request #12
Opened 2021-11-16 05:00 UTC by Nastasiya-Kam

1. Некорректная авторизация (пользователь всё время авторизован)
2. Не могу понять, когда получать фильмы из избранного. 
- Хотела сделать в момент, когда пользователь авторизируется на сайте (а до этого все фильмы же являются не в списке избранного?). Но из-за некорректной авторизации (а может из-за чего ещё), у меня ошибка выскакивает, когда я пытаюсь сделать такой код (поместить на страницу sign-in-screen код, который получает фильмы из избранного). Но фильмов тогда не будет, если пользователь уже был авторизован до того, как перейти на страницу sign in...
- ещё была мысль получать их в момент старта приложения ЕСЛИ, пользователь авторизован. Но я пока не понимаю как делать эту проверку (это всё выливается из пункта один, где я не понимаю авторизацию совсем)
3. А ещё я хотела сделать "пальчик" при наведении на карточки фильмов, но не нашла места, куда это прописать (прописывала в main.css (project/public/css) `small-film-card` или `small-film-card__image` )
![image](https://user-images.githubusercontent.com/68639052/141923522-08ad49e4-b7f0-4f8c-9994-f9b6ac2d3c94.png)
4. С фоном в комментариях я не совсем поняла, там "большой" розовый поправила, но в форме другой цвет. Туда нужно какой-то другой передавать или оставить розовым?

2021-11-16 14:49 UTC, raccoonlemon commented
Некорректная авторизация (пользователь всё время авторизован).

Ты похоже не дошла в демо-проекте до коммита
https://github.com/htmlacademy-react/guess-melody-8/pull/6/commits/cb32c099fae9359ee090ec3beebbd4c49af2ece8

Ничего, я тоже на этом обулась, и долго искала. И еще люди помимо нас с тобой) В итоге пошла разбираться почему это у них работает, а у меня нет)))
![image](https://user-images.githubusercontent.com/71271294/142007481-815c6e57-d63e-461b-aea2-0f24a57e8307.png)

Вот и весь фикс. Из-за того что был return промис не реджектился.

2021-11-16 14:56 UTC, raccoonlemon commented
Получение фильмов из избранного.

Я думаю можно получать избранные фильмы при переходе на страницу. Неавторизованный пользователь туда зайти не может. Ну и заранее их получать - такое себе, может пользователь вообще туда не пойдет, а мы лишний запрос сделаем. Плюс, если их получать только на старте - то при нажатии кнопки добавления в избранное надо будет там эти фильмы апдейтить в сторе.

В ТЗ такое написано:
"Данные для страницы «MyList» всегда загружаются с сервера. Для этого предусмотрен отдельный маршрут (см. раздел «Взаимодействие с сервером»)."

Еще кстати кнопочку добавление в избранное не надо наверное показывать для неавторизированных. Чет я правда в ТЗ не нашла по этому поводу ничего.

2021-11-16 15:05 UTC, raccoonlemon commented
Для того чтобы пальчик был - у тебя код рабочий, проверила в баузере, добавила в стиль.
Но у нас к странице подключается минифицированный файл. Там руками редактировать не очень то весело =)
`<link rel="stylesheet" href="css/main.min.css">`
![image](https://user-images.githubusercontent.com/71271294/142010317-50963086-48bb-4936-9917-a8bb446f460f.png)

2021-11-16 15:12 UTC, raccoonlemon commented
По поводу фона - хороший вопрос, но тут наверное на твое усмотрение. С сервера я не вижу чтобы доп.цвета приходили. 

Можно для страницы отзыва вообще не менять цвет, пусть все розовое.

Или как вариант, я сделала ее белую полупрозрачную. Но тогда и текст становится немного прозрачный.
![image](https://user-images.githubusercontent.com/71271294/142011389-c73c473f-9ae3-43bd-9bdc-6083171b1476.png)

Или можно еще придумать какие-нибудь изощренные способы, но возни много, пользы мало =)

2021-11-16 17:34 UTC, Nastasiya-Kam commented
> Получение фильмов из избранного.
> 
> Я думаю можно получать избранные фильмы при переходе на страницу. Неавторизованный пользователь туда зайти не может. Ну и заранее их получать - такое себе, может пользователь вообще туда не пойдет, а мы лишний запрос сделаем. Плюс, если их получать только на старте - то при нажатии кнопки добавления в избранное надо будет там эти фильмы апдейтить в сторе.

а как тогда я кнопочкам дам понять, что они в избранном, если заранее список избранного не получу? они же при входе (в простом списке фильмов) все не в избранном. А кнопку уже отметить нужно
 
> В ТЗ такое написано: "Данные для страницы «MyList» всегда загружаются с сервера. Для этого предусмотрен отдельный маршрут (см. раздел «Взаимодействие с сервером»)."
> 
> Еще кстати кнопочку добавление в избранное не надо наверное показывать для неавторизированных. Чет я правда в ТЗ не нашла по этому поводу ничего.

этого тоже не нашла, вопросик возникал. Ну как вариант, при нажатии на кнопку избранного, если ты не авторизован, то перекидывать на страницу авторизации... мне кажется такое делают на многих сайтах в жизни. Либо какое-то сообщение

2021-11-16 17:36 UTC, Nastasiya-Kam commented
> Для того чтобы пальчик был - у тебя код рабочий, проверила в баузере, добавила в стиль. Но у нас к странице подключается минифицированный файл. Там руками редактировать не очень то весело =) 

я думала он каждый раз пересобирается в этот min. Нет?_)))

2021-11-16 17:40 UTC, Nastasiya-Kam commented
> По поводу фона - хороший вопрос, но тут наверное на твое усмотрение. С сервера я не вижу чтобы доп.цвета приходили.
> 
> Можно для страницы отзыва вообще не менять цвет, пусть все розовое.
> 
> Или как вариант, я сделала ее белую полупрозрачную. Но тогда и текст становится немного прозрачный. ![image]
> Или можно еще придумать какие-нибудь изощренные способы, но возни много, пользы мало =) Ну и опять же min.css редактировать не оч)

нуууууууууу... и ладненько

2021-11-20 08:54 UTC, raccoonlemon reviewed
Я неавторизованный пользователь, но у меня переключается кнопка добавления в избранное.
![image](https://user-images.githubusercontent.com/71271294/142720541-be061d12-cbe5-462f-a6d1-a572d5bbebf4.png)

2021-11-20 08:54 UTC, raccoonlemon commented on project/src/components/add-review-form/add-review-form.tsx
>    const [validRating, setValidRating] = useState(false);
validText=>isTextValid
validRating=>isRatingValid
Так понятнее, что какие-то boolean значения. 

Как вариант, эти поля хранить и необязательно.
Можно завести процедуру getIsFormValid(text, rating): boolean

2021-11-20 08:54 UTC, raccoonlemon commented on project/package.json
> +    "react-native-animated-spinkit": "^1.5.2",
react-native это для разработки мобильных приложений.

если для лоудера, то можно попробовать lotty, как вариант.
https://lottiefiles.com/blog/working-with-lottie/how-to-use-lottie-in-react-app

еще делают анимированные лоадеры с помощью анимаций на css

а вообще нам тут подойдет `<p>Loading...<p/>` ))

2021-11-20 09:02 UTC, raccoonlemon commented
Плеер наврное еще не закончент? Там время не изменяется, прогресс не двигается (штука внизу), и exit не нажимается.

Длину видео можно из самого видео получать. По нему вычисляем сколько ползунок должен за это время сдвинуться. Можно его позицию хранить в стейте, и каждую секунду изменять. 

Ну и чтобы время оставшееся менялось. Ты там правильно начала делать, через useEffect, надо туда добавить интервал каждую секунду менять значение оставшегося времени и позиции ползунка.

Для кнопки exit можно по простому сделать - через history.
![image](https://user-images.githubusercontent.com/71271294/142720722-84af02f4-dd02-4b1a-8ed5-48d5ea8506cd.png)

2021-11-20 09:05 UTC, raccoonlemon requested changes
Есть маленькие баги. Но большая работа проделана, много функционала добавилось.

2021-11-20 09:09 UTC, raccoonlemon reviewed
Вообще технически задание было про комменты, и они работают.
Если что - я могу этот пулреквест принять, как тебе удобнее.

2021-11-20 09:12 UTC, Nastasiya-Kam commented on project/package.json
> +    "react-native-animated-spinkit": "^1.5.2",
в ТЗ написано "отображается анимированный спиннер"

А я-то думаю что он у меня не работает и весь экран в красном цвете ошибок_)

2021-11-20 09:21 UTC, Nastasiya-Kam commented
> Плеер наврное еще не закончент? Там время не изменяется, прогресс не двигается (штука внизу), и exit не нажимается.


да. Пока тока кнопка плей/стоп и проигрывание видео. Но у меня не работает он, если на него зайти "вручную". Просто чёрный экран, хотя в элементах, на плеере есть и ссылка на видео и autoplay стоит. Пока не разобралась

2021-11-20 20:03 UTC, Nastasiya-Kam commented
Не знаю как делать видео проигрыватель. Ни малейшей идеи. Всё что пробую не помогает. Направление - не ясно

2021-11-21 06:39 UTC, raccoonlemon commented on project/package.json
> +    "react-native-animated-spinkit": "^1.5.2",
Издевательство какое-то а не ТЗ, как будто помимо спиннера проблем мало =)
Нашла на stackoverflow - дешево и сердито)
![image](https://user-images.githubusercontent.com/71271294/142752433-28030279-d981-4d16-bd74-7dd0a5d5becf.png)
https://stackoverflow.com/questions/8230748/how-to-add-loader-image-to-html5-video

2021-11-21 06:45 UTC, raccoonlemon approved these changes
Можно пока плеер отложить, он будет еще в 8-2 задании.
Я еще гляну, подскажу чуть позже как в плеере можно сделать.

2021-11-21 06:46 UTC, merged