Module6 task2
htmlacademy-react/1608929-what-to-watch-8 pull request #9
Opened 2021-11-04 08:20 UTC by Nastasiya-Kam

2021-11-04 13:47 UTC, raccoonlemon requested changes
Все работает =)
Есть мелкие замечания. Если вдруг пока не хочешь поправлять - отпиши в комментах просто.

2021-11-04 13:47 UTC, raccoonlemon commented on project/src/components/show-more/show-more.tsx
> +  setRenderedFilmCount: (a: number) => void;
Можно пропс setRenderedFilmCount назвать просто onClick. И не передавать сюда renderedFilmCount. Просто некая кнопка делает то что ей скажут, ей не надо подробности знать.

2021-11-04 13:47 UTC, raccoonlemon commented on project/src/utils.ts
> +const getSimilarGenreFilms = (films: Film[], genre: string) => films.filter((element) => element.genre === genre);
Надо еще учесть чтобы сюда не попал текущий открытый фильм. А то получится что он похож сам на себя.

2021-11-04 13:47 UTC, raccoonlemon commented on project/src/components/_screen/film-screen/film-screen.tsx
> +  const {id, title, genre, release, posterImage, previewImage} = films[0];
У нас теперь в URL есть id фильма, можем сюда получить уже конкретный нужный фильм по id.
Можно это сделать в роутере и сюда сразу в пропсы прокинуть фильм.
Или можно приконнектиться к стору и там найти нужный фильм, тогда вообще никакие пропсы извне передавать не надо.

2021-11-04 13:47 UTC, raccoonlemon commented on project/src/components/_screen/main-screen/main-screen.tsx
> +            : ''}
Если у тебя в тернарном операторе во втором варианте '', то лучше просто через условие.
`{hasMoreFilms && <ShowMore../>}`

2021-11-05 07:28 UTC, Nastasiya-Kam commented on project/src/components/show-more/show-more.tsx
> +  setRenderedFilmCount: (a: number) => void;
в смысле оставить функциональность, просто имя поменять? Это во всех элементах лучше так делать? А то я везде "проносила" имя ту функцию в пропы, название которой передавала

2021-11-05 07:38 UTC, Nastasiya-Kam commented on project/src/components/_screen/film-screen/film-screen.tsx
> +  const {id, title, genre, release, posterImage, previewImage} = films[0];
вот. Не поверишь. Вчера сидела обдумывала это URL, и стор. Но решила, что пока для меня стор загадка и что может об этом дальше расскажут?

2021-11-05 07:41 UTC, Nastasiya-Kam commented on project/src/components/_screen/main-screen/main-screen.tsx
> +            : ''}
что что? а как это работает???

2021-11-05 07:47 UTC, Nastasiya-Kam commented on project/src/components/_screen/main-screen/main-screen.tsx
> +            : ''}
Это был мой самый большой молчаливый вопрос, как сделать в одну строку типа if

2021-11-05 10:20 UTC, Nastasiya-Kam commented on project/src/utils.ts
> +const getSimilarGenreFilms = (films: Film[], genre: string) => films.filter((element) => element.genre === genre);
переделала. Не подумала вообще об этом

2021-11-05 10:22 UTC, Nastasiya-Kam commented on project/src/components/_screen/film-screen/film-screen.tsx
> +  const {id, title, genre, release, posterImage, previewImage} = films[0];
сделала как-то коряво... что-то я не пойму как просто взять переменную из стора. Либо мы можем взаимодействовать со стором только если произошло какое-то действие? Например, когда я переключаюсь на FilmScreen, выбирая какую-то карточку фильма, я записываю текущий фильм (currentFilm) в стор. Но как этот текущий фильм взять, чтобы кинуть его в отрисовку фильма?

2021-11-05 10:34 UTC, Nastasiya-Kam commented
Ещё вопрос про картинки. Они как-то криво вставляются на странице с описанием фильма. Это я как-то не ту картинку подставила или пока так и должно быть?

![image](https://user-images.githubusercontent.com/68639052/140497502-7ed223a1-812f-424e-b826-a3f20b64ac35.png)

2021-11-05 10:41 UTC, Nastasiya-Kam commented on project/src/utils.ts
> +const getGrade = (rating: number): string | undefined => {
вот у этой функции как корректно сделать. У меня не предусмотрен return на "что-то", что не соответствует моему грейдированию. Например, если вдруг прилетит 11, то моя функция никак это не обработает и верён undefined

Возможно, убрать if последний, раскрыть его и сделать просто

`
const getGrade = (rating: number): string | undefined => {
    if (rating < Grade.BAD.value) {
      return Grade.BAD.name;
    }
  
    if (rating < Grade.NORMAL.value && rating >= Grade.BAD.value) {
      return Grade.NORMAL.name;
    }
   ...
    return Grade.AWESOME.name;
};
`

2021-11-05 10:43 UTC, Nastasiya-Kam commented on project/src/utils.ts
> +const getSimilarGenreFilms = (films: Film[], genre: string, currentId: number): Film[] => films.filter((element) => (currentId !== element.id) && element.genre === genre);
Здесь же тоже можно применить приём с &&?

2021-11-05 15:36 UTC, raccoonlemon commented on project/src/components/show-more/show-more.tsx
> +  setRenderedFilmCount: (a: number) => void;
Мы считаем что кнопка кнопка ShowMore может нам что-то при клике сделать, если мы передадим ей пропс. Этому пропсу вполне подходит какое-то абстрактное название - onClick. А что в итоге кнопке передадут и какие там действия будут - ей по сути все равно. Поэтому тут такое конкретное название setRenderedFilmCount излишне. Таким образом мы уменьшаем связность компонентов друг с другом (есть такое понятие coupling в программировании). Может мы бы потенциально эту кнопку могли еще где-то использовать, и она бы там не увеличивала количество фильмов, а что-то другое делала.

Чем абстрактнее, независимее и глупее компонент, и чем проще его заменить на другой - тем лучше. Но слишком увлекаться тоже не нужно. Мы теоретически предполагаем что можем использовать его где-то еще. Но суперуниверсально делать тоже не нужно. Делать все-все универсально и пытаться предусмотреть все случаи - другая крайность. Придерживаемся золотой середины.

2021-11-05 15:38 UTC, raccoonlemon commented on project/src/components/_screen/main-screen/main-screen.tsx
> +            : ''}
Вообще странно что это не показали на лекциях. Это условный рендеринг, типа если условие hasMoreFilms=true, то компонент выведется. Если false, то нет =)
Тут еще есть варианты:
https://ru.reactjs.org/docs/conditional-rendering.html

2021-11-05 15:39 UTC, raccoonlemon commented on project/src/utils.ts
> +const getSimilarGenreFilms = (films: Film[], genre: string, currentId: number): Film[] => films.filter((element) => (currentId !== element.id) && element.genre === genre);
Угу)

2021-11-05 15:42 UTC, raccoonlemon commented
> Ещё вопрос про картинки. Они как-то криво вставляются на странице с описанием фильма. Это я как-то не ту картинку подставила или пока так и должно быть?
> 
> ![image](https://user-images.githubusercontent.com/68639052/140497502-7ed223a1-812f-424e-b826-a3f20b64ac35.png)

Угу, ничего страшного. В моках просто картинки неподходящего размера. Когда с сервера придут - все ок будет. Там еще цвет подложки кажется будет с сервера приходить и картинка фоновая.

2021-11-05 16:12 UTC, raccoonlemon commented on project/src/components/_screen/film-screen/film-screen.tsx
> +  const {id, title, genre, release, posterImage, previewImage} = films[0];
Есть такой вариант:
![image](https://user-images.githubusercontent.com/71271294/140542569-8c769538-0a56-4101-86f8-fe743baa7891.png)
![image](https://user-images.githubusercontent.com/71271294/140542639-209b9597-fbc7-42fd-bf66-65b516512316.png)

2021-11-05 16:13 UTC, raccoonlemon commented on project/src/components/_screen/film-screen/film-screen.tsx
> +  const {id, title, genre, release, posterImage, previewImage} = films[0];
В принципе нам в данном случае в стор никаких действий отсылать не нужно, и текущий фильм в сторе хранить тоже не обязательно.

2021-11-05 16:17 UTC, raccoonlemon commented on project/src/components/_screen/film-screen/film-screen.tsx
> +  const {id, title, genre, release, posterImage, previewImage} = films[0];
Но можно сделать и с хранением в сторе. Например мы получаем фильм с сервера, прямо тут в компоненте.
Т.е у нас там будет что-то типа fetch, и там по итогу как раз можно сделать:
`dispatch(setCurrentFilm(currentFilm)`

Но тогда надо будет предусмотреть состояние компонента на момент когда фильм еще не загружен и выводить надпись типа loading.

Стор - это у нас хранилище куда мы складываем данные, допустим сложили фильмы. Можем любой компонент приконнектить - и у нас будет к ним доступ.

Если нам надо в сторе что-то изменить - то делаем dispatch. По итогу состояние меняется, и компоненты которые мы приконнектили - они обновятся. Типа как паттерн Observer у нас был на JS 2, когда презентеры подписывались на обновление модели.

2021-11-05 16:19 UTC, raccoonlemon commented on project/src/components/_screen/film-screen/film-screen.tsx
> +  const {id, title, genre, release, posterImage, previewImage} = films[0];
Про ownProps можно тут почитать
https://react-redux.js.org/api/connect#mapstatetoprops-state-ownprops--object

2021-11-05 17:58 UTC, raccoonlemon approved these changes
Принято)

2021-11-05 17:58 UTC, merged